name: Run Postman Collection on Windows with HTML Reporter

on:
  workflow_dispatch:

jobs:
  run-postman-collection:
    runs-on: windows-latest

    steps:
      # Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install Newman and HTML Reporter
      - name: Install Newman and HTML Reporter
        shell: pwsh
        run: 
          npm install -g newman
      - name: Install Html Reporter
        shell: pwsh
        run:
          npm install -g newman-reporter-htmlextra

      # Export HTML Report
      - name: Run Postman Trello.postman_collection
        shell: pwsh
        run: |
          newman run ".\Trello.postman_collection.json" -e ".\Trello.postman_environment.json" -r htmlextra --reporter-htmlextra-export newman-report.html\report.html


      # Upload HTML Report as artifact
      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: postman-html-report
          path: newman-report.html
